module.exports  = {
    products:[
        {
            name:'小米小电视',
            description:'优质、优惠、优美',
            price:'550',
        },
        {
            name:'小米中电视',
            description:'优质、优惠、优美',
            price:'1550',
        },
        {
            name:'小米大电视',
            description:'优质、优惠、优美',
            price:'2550',
        },
        {
            name:'小米巨大电视',
            description:'优质、优惠、优美',
            price:'3550',
        },
        {
            name:'小米小电视',
            description:'优质、优惠、优美',
            price:'550',
        },
        {
            name:'小米中电视',
            description:'优质、优惠、优美',
            price:'1550',
        },
        {
            name:'小米大电视',
            description:'优质、优惠、优美',
            price:'2550',
        },
        {
            name:'小米巨大电视',
            description:'优质、优惠、优美',
            price:'3550',
        }
    ]
}